# Based on https://github.com/actions-rs/meta/blob/master/recipes/matrix.md

on: push

name: Build

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          #- 1.51.0  # MSRV
        experimental: [false]
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  coverage-codecov:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tarpaulin for codecov.io
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'
          args: '--ciserver github-ci --all-features --ignore-tests'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2